version: "3.7"

services:
  client:
    build:
      context: .
      target: client-dev
    command: yarn start
    tty: true
    environment:
      PORT: 13000
    ports:
      - 13000:13000
    volumes:
      - ./client:/client
